### ISSUE TITLE
Dragonfly scripts without aenea

### ISSUE THREAD

**Issue by truthbeliever** [dictation-toolbox/dragonfly-scripts#32]
Hello,

I copied all the scripts in the corresponding natlink folder and they all require Aenea to run. I copied some Aena Client and now its requesting jsonlibrpc ..... 
But I want to work only locally on my windows 8 machine without any Virtualmachine doing coding in Visual Studio.

Is there a switch to set like "do not use aenea", so that all the scripts run locally without aenea?

Thank you

**Comment by nirvdrum** [comment]
It looks like I accidentally introduced the hard dependency when upgrading to the latest aenea. In the meanwhile, try checking out the pre_aenea_reorganization tag.

**Comment by davidmrichter** [comment]
I took the files from the pre_aenea_reorganization repository and copied them to the NatLink NATLink MacroSystem folder.
I created config.json
{
	"aenea.enabled": false,
    "aenea.path": null, 
    "dynamics.bash.enabled": false,
    "dynamics.css.enabled": false,
    "dynamics.git.enabled": false,
    "dynamics.html.enabled": false,
    "dynamics.javascript.enabled": false,
    "dynamics.python.enabled": false,
    "system.base_path": "C:\\Natlink\\Natlink\\MacroSystem"
}

resulting in this error:

\_generic_edit.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 340, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\NatLink\NatLink\MacroSystem\_generic_edit.py", line 30, in <module>
    from lib.dynamic_aenea import (
  File "C:\NatLink\NatLink\MacroSystem\lib\dynamic_aenea.py", line 1, in <module>
    import aenea, dragonfly, proxy_actions, lib.config
ImportError: No module named aenea

But then if I "install" Aenea client, then its requesting jsonlib

I appreciate any hint as to use the scripts without aenea.

Thank you

**Comment by nirvdrum** [comment]
I guess this has been tied to aenea for longer than I've realized. You can keep digging back through history, but until I'm able to spend some time to split the two apart, you may be better off just installing aenea as well.

**Comment by davidmrichter** [comment]
I copied Aenea client and somehow adjusted aenea.json.

Error loading _vocabulary from C:\NatLink\NatLink\MacroSystem\_vocabulary.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 340, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\NatLink\NatLink\MacroSystem\_vocabulary.py", line 23, in <module>
    import aenea.vocabulary
  File "C:\NatLink\NatLink\MacroSystem\aenea\__init__.py", line 18, in <module>
    import aenea.communications
  File "C:\NatLink\NatLink\MacroSystem\aenea\communications.py", line 19, in <module>
    import jsonrpclib
ImportError: No module named jsonrpclib

So I copy jsonrpclib to the macrofolder

Then 
Error loading _vocabulary from C:\NatLink\NatLink\MacroSystem\_vocabulary.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 340, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\NatLink\NatLink\MacroSystem\_vocabulary.py", line 23, in <module>
    import aenea.vocabulary
  File "C:\NatLink\NatLink\MacroSystem\aenea\__init__.py", line 22, in <module>
    import aenea.lax
  File "C:\NatLink\NatLink\MacroSystem\aenea\lax.py", line 25, in <module>
    import aenea.proxy_actions
  File "C:\NatLink\NatLink\MacroSystem\aenea\proxy_actions.py", line 85, in <module>
    class ProxyKey(ProxyBase, dragonfly.DynStrActionBase):
  File "C:\NatLink\NatLink\MacroSystem\aenea\proxy_actions.py", line 90, in ProxyKey
    _parser = _make_key_parser()
  File "C:\NatLink\NatLink\MacroSystem\aenea\proxy_actions.py", line 43, in _make_key_parser
    from pyparsing import (Optional, Literal, Word, Group, Keyword,
ImportError: No module named pyparsing

I do not need proxies etc. 
Any idea what do I wrong with the aenea client installation on win8?

**Comment by davidmrichter** [comment]
I stripped all scripts I require from aenea by hand, so I can start working with the scripts.

Could you inform me as soon as you might have deconnected aenea from the scripts?

Thank you

**Comment by BawdyInkSlinger** [comment]
is anyone working on this? These scripts seem really useful but I can't use them because of this.
